import type * as Ru from "../ru/errors";

/** What goes on screen when something fails. */
export const errors: typeof Ru.errors = {
  generic: "Didn't work",
  network: "Network is not responding",
  saveFailed: "Couldn't save",
  runFailed: "Generation failed",
  slotsFull: "All contracts are taken. Close or skip a game first.",
  poolEmpty: "No games available. Sync your library.",
  noFreeSkips: "No free skips left",
  runInProgress: "A run is already in progress",
  needReviews: (need: number, have: number) => `Needs at least ${need} reviews, you have ${have}`,
  noCandidates: "No unplayed games left in the library",
  runFailedFallback: "Couldn't get the recommendations",
  modelBusy: "The model is overloaded right now. Try again in a couple of minutes — it's temporary.",
  modelQuota: "The request quota for the model is used up. Try later — it resets on its own.",
  modelQuotaDay: "The daily request quota for the model is used up — it resets at the start of the next day.",
  modelNoCredit: "The provider refused to bill the request: no funds left, or a spend limit was reached. Check the billing where the key came from.",
  badRequest: "Malformed request",
  noGame: "No game specified",
  gameNotFound: "Game not found",
  contractNotFound: "Contract not found",
  userNotFound: "User not found",
  unknownMode: "Unknown mode",
  badVerdict: "Invalid verdict",
  badTier: "Invalid tier",
  badRating: "Rating must be 1 to 5",
  needAppId: "Enter a Steam appid or a link to the demo page",
  steamNotFound: "No game in Steam with that appid",
  gameNotOwned: "That game isn't in your library",
  contractExists: "You already have a contract on this game",
  recordNotFound: "Nothing recorded for this game yet",
  noVerdict: "Pick a verdict",
  noContract: "No contract specified",
  noteTooShort: (min: number) => `The note needs at least ${min} characters`,
  notEnoughPlaytime: (need: number, played: number) =>
    `Play at least ${need} minutes first — you're at ${played}`,
  noEntry: "No entry specified",
  entryNotFound: "Entry not found",
  noTag: "No tag specified",
  badTagLabel: "A tag is 2 to 60 characters",
};
