/** What goes on screen when something fails. */
export const errors = {
  generic: "Не получилось",
  network: "Сеть не отвечает",
  saveFailed: "Не удалось сохранить",
  runFailed: "Генерация не удалась",
  slotsFull: "Все слоты заняты. Закрой или пропусти игру.",
  poolEmpty: "Нет доступных игр. Синхронизируй библиотеку.",
  noFreeSkips: "Бесплатных скипов не осталось",
  runInProgress: "Генерация уже идёт",
  needReviews: (need: number, have: number) => `Нужно минимум ${need} отзывов, сейчас ${have}`,
  noCandidates: "Нет непройденных игр в библиотеке",
  runFailedFallback: "Не удалось получить рекомендации",
  modelBusy: "Модель сейчас перегружена. Попробуй через пару минут — это временно.",
  modelQuota: "Лимит запросов к модели исчерпан. Попробуй позже — он сбрасывается сам.",
  modelQuotaDay: "Дневной лимит запросов к модели исчерпан — он сбросится в начале следующих суток.",
  modelNoCredit: "Провайдер отказал в оплате: на счету нет средств или достигнут лимит трат. Проверь биллинг там, где брал ключ.",
  badRequest: "Некорректный запрос",
  noGame: "Не указана игра",
  gameNotFound: "Игра не найдена",
  contractNotFound: "Контракт не найден",
  userNotFound: "Пользователь не найден",
  unknownMode: "Неизвестный режим",
  badVerdict: "Некорректный вердикт",
  badTier: "Некорректный тир",
  badRating: "Оценка от 1 до 5",
  needAppId: "Укажи Steam appid или ссылку на страницу демки",
  steamNotFound: "Не нашёл игру в Steam по этому appid",
  gameNotOwned: "Игра не найдена в библиотеке",
  contractExists: "Контракт на эту игру уже есть",
  recordNotFound: "Запись об игре не найдена",
  noVerdict: "Выбери вердикт",
  noContract: "Не указан контракт",
  noteEmpty: "Напиши пару слов о том, как игра прошла",
  noteTooShort: (min: number) => `Заметка минимум ${min} символов`,
  notEnoughPlaytime: (need: number, played: number) =>
    `Нужно наиграть минимум ${need} минут (сейчас ${played})`,
  noEntry: "Не указана запись",
  entryNotFound: "Запись не найдена",
  noTag: "Не указан тег",
  badTagLabel: "Тег от 2 до 60 знаков",
};
